-- Auto-generated by prisma migrate
-- Fase: ciudades → departamentos (enfoque no destructivo)

-- 1. Create WarehouseServedDepartment table (replaces WarehouseServedCity concept)
CREATE TABLE "WarehouseServedDepartment" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "warehouseId" TEXT NOT NULL,
    "department" TEXT NOT NULL,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "WarehouseServedDepartment_tenantId_warehouseId_department_key"
    ON "WarehouseServedDepartment"("tenantId", "warehouseId", "department");
CREATE UNIQUE INDEX "WarehouseServedDepartment_tenantId_department_key"
    ON "WarehouseServedDepartment"("tenantId", "department");
CREATE INDEX "WarehouseServedDepartment_tenantId_department_idx"
    ON "WarehouseServedDepartment"("tenantId", "department");

-- 2. Add department columns (nullable — non destructive)
ALTER TABLE "Warehouse" ADD COLUMN "department" TEXT;
ALTER TABLE "Customer" ADD COLUMN "department" TEXT;
ALTER TABLE "Quote" ADD COLUMN "deliveryDepartment" TEXT;
ALTER TABLE "SalesOrder" ADD COLUMN "deliveryDepartment" TEXT;
ALTER TABLE "SupplyPurchaseList" ADD COLUMN "department" TEXT;
ALTER TABLE "StockMovementRequest" ADD COLUMN "requestedDepartment" TEXT;
ALTER TABLE "Notification" ADD COLUMN "department" TEXT;

-- 3. Indexes for new department columns
CREATE INDEX "StockMovementRequest_tenantId_requestedDepartment_idx"
    ON "StockMovementRequest"("tenantId", "requestedDepartment");
CREATE INDEX "StockMovementRequest_tenantId_requestedDepartment_status_idx"
    ON "StockMovementRequest"("tenantId", "requestedDepartment", "status");

-- 4. Backfill: map existing city values to departments (Bolivia)
-- The mapping covers the 9 Bolivian departments. Unmapped cities retain their value.
DO $$
DECLARE
    r RECORD;
    dept TEXT;
BEGIN
    -- Map Warehouse.city → Warehouse.department
    FOR r IN SELECT id, city FROM "Warehouse" WHERE city IS NOT NULL
    LOOP
        dept := CASE UPPER(TRIM(r.city))
            WHEN 'LA PAZ' THEN 'LA PAZ'
            WHEN 'EL ALTO' THEN 'LA PAZ'
            WHEN 'VIACHA' THEN 'LA PAZ'
            WHEN 'COPEPAZ' THEN 'LA PAZ'
            WHEN 'COCHABAMBA' THEN 'COCHABAMBA'
            WHEN 'SANTA CRUZ' THEN 'SANTA CRUZ'
            WHEN 'ORURO' THEN 'ORURO'
            WHEN 'POTOSI' THEN 'POTOSÍ'
            WHEN 'POTOSÍ' THEN 'POTOSÍ'
            WHEN 'SUCRE' THEN 'CHUQUISACA'
            WHEN 'TARIJA' THEN 'TARIJA'
            WHEN 'TRINIDAD' THEN 'BENI'
            WHEN 'COBIJA' THEN 'PANDO'
            WHEN 'PANDO' THEN 'PANDO'
            ELSE UPPER(TRIM(r.city))
        END;

        UPDATE "Warehouse" SET department = dept WHERE id = r.id;
    END LOOP;

    -- Map Customer.city → Customer.department
    FOR r IN SELECT id, city FROM "Customer" WHERE city IS NOT NULL
    LOOP
        dept := CASE UPPER(TRIM(r.city))
            WHEN 'LA PAZ' THEN 'LA PAZ'
            WHEN 'EL ALTO' THEN 'LA PAZ'
            WHEN 'VIACHA' THEN 'LA PAZ'
            WHEN 'COPEPAZ' THEN 'LA PAZ'
            WHEN 'COCHABAMBA' THEN 'COCHABAMBA'
            WHEN 'SANTA CRUZ' THEN 'SANTA CRUZ'
            WHEN 'ORURO' THEN 'ORURO'
            WHEN 'POTOSI' THEN 'POTOSÍ'
            WHEN 'POTOSÍ' THEN 'POTOSÍ'
            WHEN 'SUCRE' THEN 'CHUQUISACA'
            WHEN 'TARIJA' THEN 'TARIJA'
            WHEN 'TRINIDAD' THEN 'BENI'
            WHEN 'COBIJA' THEN 'PANDO'
            WHEN 'PANDO' THEN 'PANDO'
            ELSE UPPER(TRIM(r.city))
        END;

        UPDATE "Customer" SET department = dept WHERE id = r.id;
    END LOOP;

    -- Map Quote.deliveryCity → Quote.deliveryDepartment
    FOR r IN SELECT id, "deliveryCity" FROM "Quote" WHERE "deliveryCity" IS NOT NULL
    LOOP
        dept := CASE UPPER(TRIM(r."deliveryCity"))
            WHEN 'LA PAZ' THEN 'LA PAZ'
            WHEN 'EL ALTO' THEN 'LA PAZ'
            WHEN 'VIACHA' THEN 'LA PAZ'
            WHEN 'COPEPAZ' THEN 'LA PAZ'
            WHEN 'COCHABAMBA' THEN 'COCHABAMBA'
            WHEN 'SANTA CRUZ' THEN 'SANTA CRUZ'
            WHEN 'ORURO' THEN 'ORURO'
            WHEN 'POTOSI' THEN 'POTOSÍ'
            WHEN 'POTOSÍ' THEN 'POTOSÍ'
            WHEN 'SUCRE' THEN 'CHUQUISACA'
            WHEN 'TARIJA' THEN 'TARIJA'
            WHEN 'TRINIDAD' THEN 'BENI'
            WHEN 'COBIJA' THEN 'PANDO'
            WHEN 'PANDO' THEN 'PANDO'
            ELSE UPPER(TRIM(r."deliveryCity"))
        END;

        UPDATE "Quote" SET "deliveryDepartment" = dept WHERE id = r.id;
    END LOOP;

    -- Map SalesOrder.deliveryCity → SalesOrder.deliveryDepartment
    FOR r IN SELECT id, "deliveryCity" FROM "SalesOrder" WHERE "deliveryCity" IS NOT NULL
    LOOP
        dept := CASE UPPER(TRIM(r."deliveryCity"))
            WHEN 'LA PAZ' THEN 'LA PAZ'
            WHEN 'EL ALTO' THEN 'LA PAZ'
            WHEN 'VIACHA' THEN 'LA PAZ'
            WHEN 'COPEPAZ' THEN 'LA PAZ'
            WHEN 'COCHABAMBA' THEN 'COCHABAMBA'
            WHEN 'SANTA CRUZ' THEN 'SANTA CRUZ'
            WHEN 'ORURO' THEN 'ORURO'
            WHEN 'POTOSI' THEN 'POTOSÍ'
            WHEN 'POTOSÍ' THEN 'POTOSÍ'
            WHEN 'SUCRE' THEN 'CHUQUISACA'
            WHEN 'TARIJA' THEN 'TARIJA'
            WHEN 'TRINIDAD' THEN 'BENI'
            WHEN 'COBIJA' THEN 'PANDO'
            WHEN 'PANDO' THEN 'PANDO'
            ELSE UPPER(TRIM(r."deliveryCity"))
        END;

        UPDATE "SalesOrder" SET "deliveryDepartment" = dept WHERE id = r.id;
    END LOOP;

    -- Map SupplyPurchaseList.city → SupplyPurchaseList.department
    FOR r IN SELECT id, city FROM "SupplyPurchaseList" WHERE city IS NOT NULL
    LOOP
        dept := CASE UPPER(TRIM(r.city))
            WHEN 'LA PAZ' THEN 'LA PAZ'
            WHEN 'EL ALTO' THEN 'LA PAZ'
            WHEN 'VIACHA' THEN 'LA PAZ'
            WHEN 'COPEPAZ' THEN 'LA PAZ'
            WHEN 'COCHABAMBA' THEN 'COCHABAMBA'
            WHEN 'SANTA CRUZ' THEN 'SANTA CRUZ'
            WHEN 'ORURO' THEN 'ORURO'
            WHEN 'POTOSI' THEN 'POTOSÍ'
            WHEN 'POTOSÍ' THEN 'POTOSÍ'
            WHEN 'SUCRE' THEN 'CHUQUISACA'
            WHEN 'TARIJA' THEN 'TARIJA'
            WHEN 'TRINIDAD' THEN 'BENI'
            WHEN 'COBIJA' THEN 'PANDO'
            WHEN 'PANDO' THEN 'PANDO'
            ELSE UPPER(TRIM(r.city))
        END;

        UPDATE "SupplyPurchaseList" SET department = dept WHERE id = r.id;
    END LOOP;

    -- Map StockMovementRequest.requestedCity → StockMovementRequest.requestedDepartment
    FOR r IN SELECT id, "requestedCity" FROM "StockMovementRequest" WHERE "requestedCity" IS NOT NULL
    LOOP
        dept := CASE UPPER(TRIM(r."requestedCity"))
            WHEN 'LA PAZ' THEN 'LA PAZ'
            WHEN 'EL ALTO' THEN 'LA PAZ'
            WHEN 'VIACHA' THEN 'LA PAZ'
            WHEN 'COPEPAZ' THEN 'LA PAZ'
            WHEN 'COCHABAMBA' THEN 'COCHABAMBA'
            WHEN 'SANTA CRUZ' THEN 'SANTA CRUZ'
            WHEN 'ORURO' THEN 'ORURO'
            WHEN 'POTOSI' THEN 'POTOSÍ'
            WHEN 'POTOSÍ' THEN 'POTOSÍ'
            WHEN 'SUCRE' THEN 'CHUQUISACA'
            WHEN 'TARIJA' THEN 'TARIJA'
            WHEN 'TRINIDAD' THEN 'BENI'
            WHEN 'COBIJA' THEN 'PANDO'
            WHEN 'PANDO' THEN 'PANDO'
            ELSE UPPER(TRIM(r."requestedCity"))
        END;

        UPDATE "StockMovementRequest" SET "requestedDepartment" = dept WHERE id = r.id;
    END LOOP;

    -- Backfill Notification.department from Warehouse.department (when warehouseId is set)
    UPDATE "Notification" n
    SET department = w.department
    FROM "Warehouse" w
    WHERE n."warehouseId" = w.id AND w.department IS NOT NULL AND n.department IS NULL;

    -- For remaining notifications with city but no warehouseId, map city → department
    -- (These are city-scoped legacy notifications)
    -- Using a simple CASE/UPDATE instead of PL/pgSQL for the notification table
    -- Since this may affect many rows, we use a single UPDATE with CASE
    UPDATE "Notification"
    SET department = CASE UPPER(TRIM(city))
      WHEN 'LA PAZ' THEN 'LA PAZ'
      WHEN 'EL ALTO' THEN 'LA PAZ'
      WHEN 'VIACHA' THEN 'LA PAZ'
      WHEN 'COCHABAMBA' THEN 'COCHABAMBA'
      WHEN 'SANTA CRUZ' THEN 'SANTA CRUZ'
      WHEN 'ORURO' THEN 'ORURO'
      WHEN 'POTOSI' THEN 'POTOSÍ'
      WHEN 'POTOSÍ' THEN 'POTOSÍ'
      WHEN 'SUCRE' THEN 'CHUQUISACA'
      WHEN 'TARIJA' THEN 'TARIJA'
      WHEN 'TRINIDAD' THEN 'BENI'
      WHEN 'COBIJA' THEN 'PANDO'
      WHEN 'PANDO' THEN 'PANDO'
      ELSE UPPER(TRIM(city))
    END
    WHERE city IS NOT NULL AND department IS NULL;
  END $$;

-- 5. Backfill: seed WarehouseServedDepartment from Warehouse.department (each SALES warehouse serves its own department)
INSERT INTO "WarehouseServedDepartment" (id, "tenantId", "warehouseId", "department")
SELECT gen_random_uuid(), w."tenantId", w.id, UPPER(TRIM(w.department))
FROM "Warehouse" w
WHERE w.department IS NOT NULL AND w.type = 'SALES';
