# Snippet: add this to a project's docker-compose.yml if you want the project itself
# to ensure its bucket exists (and public read) without editing /minio compose.
#
# Requires the project to join the same external network: red-interna
# and MINIO_ROOT_* (or a less-privileged access key) to be available.

services:
  bucket-init:
    image: minio/mc:latest
    restart: "no"
    networks:
      - red-interna
    environment:
      MINIO_ENDPOINT_INTERNAL: ${MINIO_ENDPOINT_INTERNAL:-http://minio-principal:9000}
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY_ID}
      MINIO_SECRET_KEY: ${S3_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${S3_BUCKET}
    entrypoint: ["/bin/sh", "-lc"]
    command:
      - |
        set -e
        echo "[bucket-init] Waiting for MinIO..."
        for i in $(seq 1 60); do
          if mc alias set local "${MINIO_ENDPOINT_INTERNAL}" "${MINIO_ACCESS_KEY}" "${MINIO_SECRET_KEY}" >/dev/null 2>&1; then
            break
          fi
          sleep 2
        done
        BUCKET_TRIMMED=$(printf '%s' "${BUCKET_NAME}" | tr -d '[:space:]')
        mc mb -p "local/${BUCKET_TRIMMED}" || true
        mc anonymous set download "local/${BUCKET_TRIMMED}" || true
        echo "[bucket-init] Done."

networks:
  red-interna:
    external: true
