export { KPICard } from './KPICard'
export { ReportSection } from './ReportSection'
export { ExportLegend } from './ExportLegend'
export { reportColors, getChartColor, chartTooltipStyle, chartGridStyle, chartAxisStyle } from './chartTheme'
export { SalesBranchDocument } from './SalesBranchDocument'
export type { SalesBranchCustomerItem as SalesBranchDocumentCustomerItem, SalesBranchProductItem as SalesBranchDocumentProductItem, SalesBranchSummary as SalesBranchDocumentSummary } from './SalesBranchDocument'
export { SalesByDepartmentDocument } from './SalesByDepartmentDocument'
export { SalesByCustomerDocument } from './SalesByCustomerDocument'
export { SalesComparisonDocument } from './SalesComparisonDocument'
export { SalesFunnelDocument } from './SalesFunnelDocument'
export { SalesMarginsDocument } from './SalesMarginsDocument'
export { SalesMonthDocument } from './SalesMonthDocument'
export { SalesTopProductsDocument } from './SalesTopProductsDocument'
export { StockExistenciasDocument, StockExpiryDocument, StockInputsDocument, StockLowStockDocument, StockRotationDocument, StockTransfersDocument } from './StockInventoryDocuments'
export { StockOpsDocument } from './StockOpsDocument'
export type { StockOpsDocumentDepartmentItem, StockOpsDocumentReturnWarehouseItem } from './StockOpsDocument'
export { ReportSchedulesManager } from './ReportSchedulesManager'
export * from './reportsUtils'
