export { CustomersPage } from './CustomersPage'
export { CustomerDetailPage } from './CustomerDetailPage'
export { OrdersPage } from './OrdersPage'
export { OrderDetailPage } from './OrderDetailPage'
export { DeliveriesPage } from './DeliveriesPage'
export { QuotesPage } from './QuotesPage'
export { QuoteDetailPage } from './QuoteDetailPage'
export { PaymentsPage } from './PaymentsPage'
