export { CustomersPage } from './CustomersPage'
export { CustomerDetailPage } from './CustomerDetailPage'
export { OrdersPage } from './OrdersPage'
export { OrderDetailPage } from './OrderDetailPage'
export { QuotesPage } from './QuotesPage'
export { QuoteDetailPage } from './QuoteDetailPage'
